version: '3.8'
services:
  # Kind cluster in Docker
  kind-cluster:
    image: kindest/node:v1.27.3
    container_name: k8s-mcp-kind
    privileged: true
    ports:
      - "6443:6443"  # Kubernetes API
    volumes:
      - /var/lib/docker
    networks:
      - k8s-mcp

  # Test workloads
  nginx-healthy:
    image: nginx:latest
    container_name: test-nginx-healthy
    networks:
      - k8s-mcp
    depends_on:
      - kind-cluster

  nginx-problematic:
    image: nginx:nonexistent-tag
    container_name: test-nginx-problematic
    networks:
      - k8s-mcp
    depends_on:
      - kind-cluster

networks:
  k8s-mcp:
    driver: bridge