name: k8s_diagnostics_mcp_server
description: A Dart-based MCP server for Kubernetes diagnostics
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  k8s: ^1.0.0
  logging: ^1.2.0
  yaml: ^3.1.2
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.3 