name: k8s_diagnostics_mcp_server
description: A Kubernetes diagnostics MCP server built with Dart
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mcp_server: ^1.0.1
  k8s: ^1.0.0
  logging: ^1.2.0
  args: ^2.4.2
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0 