name: k8s_diagnostics_mcp_server
description: A Kubernetes diagnostics MCP server built with Dart
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # MCP Server implementation
  mcp_server: ^1.0.0
  # Kubernetes client
  k8s: ^1.0.0
  # HTTP server
  shelf: ^1.4.1
  # JSON handling
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0 