apiVersion: v1
kind: Namespace
metadata:
  name: test-problems
---
# Pod with image pull issues
apiVersion: v1
kind: Pod
metadata:
  name: bad-image-pod
  namespace: test-problems
spec:
  containers:
  - name: bad-container
    image: nonexistent/image:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
---
# Pod that crashes frequently
apiVersion: v1
kind: Pod
metadata:
  name: crash-loop-pod
  namespace: test-problems
spec:
  containers:
  - name: crash-container
    image: busybox
    command: ["sh", "-c", "sleep 10 && exit 1"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
  restartPolicy: Always
---
# Pod without resources
apiVersion: v1
kind: Pod
metadata:
  name: no-resources-pod
  namespace: test-problems
spec:
  containers:
  - name: no-resources-container
    image: nginx
---
# Elasticsearch-related pod for search testing
apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch-test
  namespace: test-problems
  labels:
    app: elasticsearch
    environment: test
spec:
  containers:
  - name: elasticsearch
    image: elasticsearch:7.17.0
    env:
    - name: discovery.type
      value: single-node
    - name: ES_JAVA_OPTS
      value: "-Xms512m -Xmx512m"
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi" 
        cpu: "1000m"